"""Distribution protocol used by analytical channel construction."""

from __future__ import annotations

from typing import Protocol

import numpy as np
from numpy.typing import ArrayLike, NDArray


class JitterDistribution(Protocol):
    """A continuous jitter law with CDF, quantiles, and controlled sampling."""

    def pdf(self, x: ArrayLike) -> NDArray[np.float64]: ...
    def cdf(self, x: ArrayLike) -> NDArray[np.float64]: ...
    def sf(self, x: ArrayLike) -> NDArray[np.float64]: ...
    def logcdf(self, x: ArrayLike) -> NDArray[np.float64]: ...
    def logsf(self, x: ArrayLike) -> NDArray[np.float64]: ...
    def ppf(self, q: ArrayLike) -> NDArray[np.float64]: ...
    def sample(
        self, size: int | tuple[int, ...], rng: np.random.Generator
    ) -> NDArray[np.float64]: ...
    def support(self) -> tuple[float, float]: ...
    def mean(self) -> float: ...
    def variance(self) -> float: ...
